labels:
  - name: invalid-forum
    labeled:
      issue:
        body: |
          This is a bug tracker and not a support forum.

          While we'd love to be able to support every person on their projects, that would simply be infeasible. Luckily, that's what the helpful developer community over at Stack Overflow is for! Please [create a question there](https://stackoverflow.com/questions/ask?tags=python+pyngrok+ngrok) if what you're looking for is a programming question or you need help with an integration. You can refer to [`hookee's` own documentation](https://hookee.readthedocs.io/en/latest/) to help you write the best possible question.
        action: close