os: linux
dist: xenial
language: python
python:
  - "2.7"
  - "3.5"
  - "3.8"
install:
  - python -m pip install virtualenv
  - python -m virtualenv venv
  - make install
script:
  - make test
  - make local
after_success:
  - codecov
before_deploy:
  - sudo -H python -m pip install setuptools twine --upgrade
  - make validate-release VERSION=$TRAVIS_TAG
deploy:
  provider: pypi
  username: alexdlaird
  password:
    secure: R5LcCX2yOuoukQClDJTj9dQ0fW6aU0rbDP8IUKY20k570XCs5/DL0W9GFjl0K0A2+CN3tT4OGFrWPC2H//HMIDxB+upoT2iIH3gn5Si0F4keo0GCG5wetjq8/++GT6QzkEBAt6heTsGAz/OfEBX57Ilews5ep0zOmQ5PKUDWoc5iaNp33A5fUoKDsOW0aRMmBtorMJ2SMd4iZ6vpBZ2+qFbuml3+MTbbohIpOTo70JVMOx+1cKSCUwAXgAO8M82xsuYzkGAaSuaoovDuxP92VoQfcfjZOpj/h02ECc5bnZl3m6Hznzq05jc63PWWTo+hc4XmkFh5fvFt+Zh8DJD23VKfQgmGGAxd40kco0RTvnjf6b2LBKTyoqBb5HCV+yCQ656a/mtIRLfopwBH63jWDpR76rysz32y6ljtX/emS2BqF/4RnAg6D8wBDgx9izOWdUDr4O6wK6csnj+pZUWdc97ub80Dltn2FceZAs9MxlyGDkjCrKROtgHqFG1I1mxZLOMsVHdzjMZt5lnGIY+BElr1pAF0qo6V3fio7DNu2ff9s6/duxeZ57z2UJ7JnikfPbBFqAkFdLGReXu8GdLD09fES83suBWLc3lhdGPE9pYh3vvTnjoSeaJzzo56qjs5yA6vfhrJLfG3KKFdOLFPU+gFo92GsfcMDS7EKAb7avA=
  on:
    tags: true
    python: "3.8"
jobs:
  include:
    - name: "OS X, Python: 3.7"
      os: osx
      language: shell
      osx_image: "xcode11.2"
      install:
        - python3 -m pip install virtualenv
        - python3 -m virtualenv venv
        - make install
    - name: "Windows, Python: 3.7"
      os: windows
      language: shell
      before_install:
        - git clone https://github.com/pyenv-win/pyenv-win.git $HOME/.pyenv
        - export PATH="$HOME/.pyenv/pyenv-win/bin:$HOME/.pyenv/pyenv-win/shims:$PATH"
        - pyenv install -q 3.7.2
        - pyenv global 3.7.2
        - pyenv rehash
        - pyenv local 3.7.2
        - python --version
        - export PATH="$HOME/.pyenv/pyenv-win/versions/3.7.2/Scripts:$PATH"
      install:
        - pip install -r requirements.txt -r requirements-dev.txt
      script:
        - nosetests -s