os: linux
dist: xenial
language: python
python:
  - "2.7"
  - "3.8"
install:
  - python -m pip install virtualenv
  - python -m virtualenv venv
  - make install
script:
  - make test
  - make local
after_success:
  - codecov
before_deploy:
  - sudo -H python -m pip install setuptools twine --upgrade
  - make validate-release VERSION=$TRAVIS_TAG
deploy:
  provider: pypi
  username: alexdlaird
  password:
    secure: R/2XXSJAfSwBqYEFFslZXeW2jXTRtsxx+ORA2MyCaW8HtNDjNgke6hFdQT9aoYuHFP0US6q0QJ6oGN80C2QgZkvM3cTPl1dcJOcpbZIovsXiVY2L2YW1DXoFuv3iXkrD+Kv6W/WfqEL5tQMmtpmS3ahNxwh6W6bItoBG5fNu5vNOtsTQWSE0MhvjDD3X/g57Cqn6MaHtqOgMdIxA56RXeC3brWH3vfprQRGBVoKJy5ZsKbuJ4E/ryY+wD0v6grNcIqy/r4+mq4rtQKnItqkyOU+Ap3kLEoDrvlXX4XMy3D/1V7Ym6JAgINCcHWSbLAU8zOUdxqkPOhrJ5DQts7Lg/6ThnKAooUrGV7LG6C8xJ2OwBD9tW8y5BmuPnHhY0t3EG8PsR3dG1Cu8bAGGCokoq9pq6XmTnI8PtjFjvs4ewzM49dxY98oGFktqrSxFJiJRF535TlU6dYCCBedlo7Dp5X9R/fgfUjWHFm5V8PsbLCuAwJpIGHqgLZoUIJSRPVlYUAJJftk2O73+XWQL6w9ysD1x1aMzvbKfoYJLV8BffKypAcJKGzgjyx5ZwFGpEZbjd1io+EgGh1MGROfv9gcjrnhW+VGEqS6qyXxUHCMsOhIL5yHVVUWxvmo7xtGXV2m7Q6nLz+lAIqwaAmW14ThUxZItqhw9lMLfCsjsYCvqnOY=
  on:
    tags: true
    python: "3.8"