os: linux
dist: xenial
language: python
python:
  - "2.7"
  - "3.5"
  - "3.8"
install:
  - python -m pip install virtualenv
  - python -m virtualenv venv
  - make install
script:
  - make test
  - make local
after_success:
  - codecov
before_deploy:
  - sudo -H python -m pip install setuptools twine --upgrade
  - make validate-release VERSION=$TRAVIS_TAG
deploy:
  provider: pypi
  username: alexdlaird
  on:
    tags: true
    python: "3.8"
jobs:
  include:
    - name: "OS X, Python: 3.7"
      os: osx
      language: shell
      osx_image: "xcode11.2"
      install:
        - python3 -m pip install virtualenv
        - python3 -m virtualenv venv
        - make install
    - name: "Windows, Python: 3.7"
      os: windows
      language: shell
      before_install:
        - git clone https://github.com/pyenv-win/pyenv-win.git $HOME/.pyenv
        - export PATH="$HOME/.pyenv/pyenv-win/bin:$HOME/.pyenv/pyenv-win/shims:$PATH"
        - pyenv install -q 3.7.2
        - pyenv global 3.7.2
        - pyenv rehash
        - pyenv local 3.7.2
        - python --version
        - export PATH="$HOME/.pyenv/pyenv-win/versions/3.7.2/Scripts:$PATH"
      install:
        - pip install -r requirements.txt -r requirements-dev.txt
      script:
        - nosetests -s