[build-system]
requires = [ "setuptools>=61.2",]
build-backend = "setuptools.build_meta"

[project]
description-file = "README.md"
dynamic = [ "version",]

[tool.setuptools]
license-files = [ "LICENSE",]
include-package-data = false