[project]
name = "hookee"
version = "2.3.3"
description = "Command line webhooks, on demand."
readme = "README.md"
license = { file = "LICENSE" }
maintainers = [{ name = "Alex Laird", email = "contact@alexlaird.com" }]
requires-python = ">=3.8"
dependencies = [
    "pluginbase>=1",
    "confuse>=1.3",
    "flask>=1.1",
    "click>=7.1",
    "pyngrok>=7.0.4",
    "defusedxml>=0.6"
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Console",
    "Environment :: Web Environment",
    "Framework :: Flask",
    "Intended Audience :: Developers",
    "Intended Audience :: Education",
    "Intended Audience :: System Administrators",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Topic :: Internet :: Proxy Servers",
    "Topic :: Internet :: WWW/HTTP :: Dynamic Content",
    "Topic :: Internet :: WWW/HTTP :: HTTP Servers",
    "Topic :: Software Development :: Testing",
]

[project.optional-dependencies]
dev = [
    "coverage[toml]",
    "requests",
    "flake8",
    "flake8-pyproject",
    "pep8-naming"
]
docs = [
    "Sphinx",
    "sphinx-notfound-page"
]

[project.scripts]
hookee = "hookee.cli:hookee"

[project.urls]
Changelog = "https://github.com/alexdlaird/hookee/blob/main/CHANGELOG.md"
Documentation = "https://hookee.readthedocs.io"
Sponsor = "https://github.com/sponsors/alexdlaird"
"Source Code" = "https://github.com/alexdlaird/hookee"

[tool.coverage.run]
omit = [
    "venv/**",
    "*/tests/**"
]

[tool.coverage.report]
precision = 2
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "if self.debug",
    "if settings.DEBUG",
    "raise AssertionError",
    "raise NotImplementedError",
    "if 0:",
    "if __name__ == .__main__.:",
]

[tool.coverage.xml]
output = "build/coverage/coverage.xml"

[tool.coverage.html]
title = "Coverage Report"
directory = "build/coverage"

[tool.flake8]
max-line-length = 119
statistics = true
exclude = "docs/*,venv/*,build/*,dist/*,.egg-info/*"