name: Validate

on:
  workflow_call:

permissions:
  contents: read
  issues: none
  pull-requests: none

jobs:
  validate:
    name: Validate

    env:
      FORCE_COLOR: 1
      PYTHONUNBUFFERED: 1
      PYTHONDONTWRITEBYTECODE: 1
      NGROK_AUTHTOKEN: ${{ secrets.NGROK_AUTHTOKEN }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: make install test
      - name: Build docs
        run: make docs
      - name: Check code
        run: make check
      - name: Validate package
        run: make local
      - name: Upload test coverage
        if: ${{ !cancelled() }}
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./build/coverage
      - name: Upload test results
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./build/test-results